---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark-jobs.fullname" . }}-secrets
  annotations: {{- include "mark-jobs.install-first.annotations" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.postgres.dbName }}"
  DATABASE_URL_DIRECT: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.postgres.dbName }}"
  REDIS_URL: {{ .Values.redis.url | quote }}
  JOB_QUEUE_SECRET: {{ .Values.jobQueue.secret | quote }}
{{- range $name, $value := .Values.secretEnv }}
  {{ $name }}: {{ $value | toString | quote }}
{{- end }}
