{{- if .Values.api.enabled -}}
{{- $params := list -}}
{{- range $k, $v := .Values.api.extraParams -}}
{{- $params = append $params (printf "%s=%s" $k ($v | toString | urlquery)) -}}
{{- end -}}
{{- if .Values.api.usePgBouncer -}}
{{- $params = append $params "pgbouncer=true" -}}
{{- end -}}
{{- $query := "" -}}
{{- if gt (len $params) 0 -}}
{{- $query = printf "?%s" (join "&" $params) -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark.api.name" $ }}-secrets
  annotations:
{{ include "mark.install-first.annotations" $ | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}{{ $query }}"
  DATABASE_URL_DIRECT: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}"
  REDIS_URL: {{ .Values.redis.url | quote }}
  JOB_QUEUE_SECRET: {{ .Values.jobQueue.secret | quote }}
{{- range $name, $value := .Values.api.secretEnv }}
  {{ $name }}: {{ $value | toString | quote }}
{{- end }}
{{- end -}}
