{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark.api.name" $ }}-secrets
  annotations:
    {{- include "mark.install-first.annotations" $ | nindent 4 }}
type: Opaque
stringData:
  {{- $params := list -}}
  {{- range $k, $v := .Values.api.extraParams }}
  {{- $params = append $params (printf "%s=%s" $k ($v | toString | urlquery)) -}}
  {{- end -}}
  {{- if .Values.api.usePgBouncer -}}
  {{- $params = append $params "pgbouncer=true" -}}
  {{- end -}}

  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}{{- if gt (len $params) 0 -}}?{{ join "&" $params }}{{- end -}}"
  DATABASE_URL_DIRECT: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}"
  {{- range $name, $value := .Values.api.secretEnv }}
  {{ $name }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
