export const JOB_WORKER_HEARTBEAT_KEY_PREFIX = "mark.jobs.worker.heartbeat";

export const DEFAULT_JOB_WORKER_HEARTBEAT_INTERVAL_MS = 10_000;
export const DEFAULT_JOB_WORKER_HEARTBEAT_TTL_SECONDS = 30;
