{{- if .Values.jobs.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mark.jobs.name" $ }}-secrets
  annotations:
{{ include "mark.install-first.annotations" $ | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}"
  DATABASE_URL_DIRECT: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.hostname }}:{{ .Values.postgres.port }}/{{ .Values.api.markDBName }}"
  REDIS_URL: {{ .Values.redis.url | quote }}
  JOB_QUEUE_SECRET: {{ .Values.jobQueue.secret | quote }}
{{- range $name, $value := .Values.jobs.secretEnv }}
  {{ $name }}: {{ $value | toString | quote }}
{{- end }}
{{- end -}}
