# Using a consistent base for all stages
ARG BASE_IMAGE=node:24-alpine
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS builder

ARG DIR=/usr/src/app

# Pruning using turbo
WORKDIR $DIR
COPY . .
RUN yarn global add turbo@^2.0.3
RUN turbo prune api-gateway --docker && rm -f .npmrc

# Installing the isolated workspace
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS installer
ARG DIR=/usr/src/app
WORKDIR $DIR
COPY --from=builder $DIR/out/json/ .
COPY --from=builder $DIR/yarn.lock ./yarn.lock
COPY --from=builder $DIR/turbo.json ./turbo.json
COPY --from=builder $DIR/packages ./packages
RUN --mount=type=cache,target=/yarn-cache,sharing=locked \
    yarn install --ignore-scripts --frozen-lockfile --cache-folder /yarn-cache

# Running build using turbo
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS sourcer
ARG DIR=/usr/src/app
WORKDIR $DIR
COPY --from=installer $DIR/ .
COPY --from=builder $DIR/out/full/ .
COPY --from=builder /usr/local/share/.config/yarn/global /usr/local/share/.config/yarn/global
RUN --mount=type=cache,target=/yarn-cache,sharing=locked \
    yarn build --filter=api-gateway \
 && yarn install --production --ignore-scripts --frozen-lockfile --cache-folder /yarn-cache

# Production stage
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS production
ARG DIR=/usr/src/app
ENV NODE_ENV=production
WORKDIR $DIR
RUN apk add --no-cache dumb-init~=1
COPY --chown=node:node --from=sourcer $DIR/apps/api-gateway/package.json ./package.json

COPY --chown=node:node --from=sourcer $DIR/apps/api-gateway/dist ./dist
COPY --chown=node:node --from=sourcer $DIR/node_modules $DIR/node_modules
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "dist/main.js"]
EXPOSE 3000

# Patched stage with updates
FROM production AS patched
USER root
RUN apk -U upgrade
USER node
