{{- if .Values.apiGateway.enabled }}
{{- with .Values.apiGateway }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mark.api-gateway.name" $ }}
  labels:
    {{- include "mark.api-gateway.labels" $ | nindent 6 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mark.api-gateway.labels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/api-gateway/secret.yaml") $ | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/api-gateway/configmap.yaml") $ | sha256sum }}
        {{- with .podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mark.api-gateway.labels" $ | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "mark.imagePullSecrets" $ | nindent 8 }}
      serviceAccountName: {{ include "mark.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "mark.api-gateway.name" $ }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{ .containerPort }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds}}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds}}
            periodSeconds: {{ .livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{ .containerPort }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds}}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds}}
            periodSeconds: {{ .livenessProbe.periodSeconds}}
          resources:
            {{- toYaml .resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "mark.api-gateway.name" $ }}-config
          - secretRef:
              name: {{ include "mark.api-gateway.name" $ }}-secrets  
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}