name: Publish Helm Chart

on:
    push:
        branches:
            - main
        paths:
            - helm-chart/**

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Helm
              uses: azure/setup-helm@v4

            - name: Build chart
              run: |
                  cd helm-chart/mark
                  helm dependency update .
                  helm package .
                  mv *.tgz ../../chart-releases/

            - name: Publish to gh-pages
              run: |
                  git checkout gh-pages
                  cp chart-releases/*.tgz .
                  helm repo index . --merge index.yaml
                  git add .
                  git commit -m "Publish chart"
                  git push origin gh-pages
